=== boxblinkracer/phpunuhi/tests/playground/xsd/phpunuhi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
>

    <xs:element name="phpunuhi">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="imports" type="typeImports" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="php" type="typePHP" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="translations" type="typeTranslations" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!-- names of Translation-Sets must be unique -->
        <xs:unique name="uniqueSetName">
            <xs:selector xpath="translations/set"/>
            <xs:field xpath="@name"/>
        </xs:unique>

    </xs:element>

    <!-- ================================================================================================================================ -->
    <!-- IMPORTS -->

    <!-- Define complex types -->
    <xs:complexType name="typeImports">
        <xs:sequence>
            <xs:element name="import" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="resource" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ================================================================================================================================ -->
    <!-- PHP ENV -->

    <xs:complexType name="typePHP">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="env" type="typePHPEnv" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="typePHPEnv">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="value" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- ================================================================================================================================ -->
    <!-- TRANSLATION-SETS -->

    <xs:complexType name="typeTranslations">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="set" type="typeTranslationSet" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="typeTranslationSet">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="format" type="typeFormat" minOccurs="1" maxOccurs="1"/>
            <xs:element name="protect" type="typeProtect" minOccurs="0" maxOccurs="1"/>
            <xs:element name="filter" type="typeFilter" minOccurs="0" maxOccurs="1"/>
            <xs:element name="rules" type="typeRules" minOccurs="0" maxOccurs="1"/>
            <xs:element name="styles" type="typeStyle" minOccurs="0" maxOccurs="1"/>
            <xs:element name="locales" type="typeLocales" minOccurs="1" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- ================================================================================================================================ -->
    <!-- PROTECTION -->

    <xs:complexType name="typeProtect">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="marker" type="typeProtectMarker" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="term" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="typeProtectMarker">
        <xs:attribute name="start" type="xs:string" use="required"/>
        <xs:attribute name="end" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- ================================================================================================================================ -->
    <!-- FILTER -->

    <xs:complexType name="typeFilter">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="include" type="typeFilterKey" minOccurs="0" maxOccurs="1"/>
            <xs:element name="exclude" type="typeFilterKey" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="typeFilterKey">
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:element name="key" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <!-- ================================================================================================================================ -->
    <!-- RULES -->

    <xs:complexType name="typeRules">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="nestingDepth" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="keyLength" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="disallowedTexts" type="typeDisallowedText" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="duplicateContent" type="xs:boolean" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="typeDisallowedText">
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <!-- ================================================================================================================================ -->
    <!-- STYLE -->

    <xs:complexType name="typeStyle">
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:element name="style" type="styleOptions" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="styleOptions">
        <xs:simpleContent>
            <xs:extension base="styleOptionValueType">
                <xs:attribute name="level" type="xs:int" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="styleOptionValueType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="camel"/>
            <xs:enumeration value="snake"/>
            <xs:enumeration value="kebab"/>
            <xs:enumeration value="lower"/>
            <xs:enumeration value="upper"/>
            <xs:enumeration value="pascal"/>
            <xs:enumeration value="start"/>
            <xs:enumeration value="number"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- ================================================================================================================================ -->
    <!-- LOCALES -->

    <xs:complexType name="typeLocales">
        <xs:sequence>
            <xs:element name="locale" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="iniSection" type="xs:string" use="optional"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="basePath" type="xs:string" use="optional"/>
    </xs:complexType>

    <!-- ================================================================================================================================ -->
    <!-- STORAGE FORMATS -->

    <xs:complexType name="typeFormat">
        <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element name="json" type="typeFormatJSON" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="ini" type="typeFormatINI" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="po" type="typeFormatPO" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="php" type="typeFormatPHP" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="shopware6" type="typeFormatShopware6" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="yaml" type="typeFormatYAML" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="typeFormatJSON">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="indent" type="xs:string" use="optional"/>
                <xs:attribute name="sort" type="xs:boolean" use="optional"/>
                <xs:attribute name="eol-last" type="xs:boolean" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typeFormatINI">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="sort" type="xs:boolean" use="optional"/>
                <xs:attribute name="eol-last" type="xs:boolean" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typeFormatPO">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="eol-last" type="xs:boolean" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typeFormatPHP">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="indent" type="xs:string" use="optional"/>
                <xs:attribute name="sort" type="xs:boolean" use="optional"/>
                <xs:attribute name="eol-last" type="xs:boolean" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typeFormatShopware6">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="entity" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="typeFormatYAML">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="indent" type="xs:string" use="optional"/>
                <xs:attribute name="sort" type="xs:boolean" use="optional"/>
                <xs:attribute name="eol-last" type="xs:boolean" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- ================================================================================================================================ -->

</xs:schema>

=== boxblinkracer/phpunuhi/tests/playground/po/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../xsd/phpunuhi.xsd"
>

    <translations>

        <set name="po">
            <format>
                <po />
            </format>
            <locales>
                <locale name="de">./%locale%.po</locale>
                <locale name="en">./%locale%.po</locale>
                <locale name="fr">./%locale%.po</locale>
            </locales>
        </set>

    </translations>

</phpunuhi>

=== boxblinkracer/phpunuhi/tests/playground/xsd/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="phpunuhi.xsd"
>

    <php>
        <env name="DB_HOST" value="127.0.0.1"/>
        <env name="DB_PORT" value="3306"/>
        <env name="DB_USER" value=""/>
        <env name="DB_PASSWD" value=""/>
        <env name="DB_DBNAME" value=""/>
    </php>

    <translations>

        <set name="json">
            <format>
                <json indent="2" sort="true"></json>
            </format>
            <locales>
                <locale name="de">./snippets/storefront/de.json</locale>
                <locale name="en">./snippets/storefront/en.json</locale>
            </locales>
        </set>

        <set name="ini">
            <format>
                <ini sort="true"></ini>
            </format>
            <locales>
                <locale name="de" iniSection="de">./snippets/storefront/de.json</locale>
                <locale name="en" iniSection="en">./snippets/storefront/en.json</locale>
            </locales>
        </set>

        <set name="php">
            <format>
                <php indent="2" sort="true"></php>
            </format>
            <locales>
                <locale name="de">./snippets/storefront/de.php</locale>
                <locale name="en">./snippets/storefront/en.php</locale>
            </locales>
        </set>

        <set name="shopware6">
            <format>
                <shopware6 entity="product"></shopware6>
            </format>
            <filter>
                <include>
                    <key>abc</key>
                </include>
                <exclude>
                    <key>abc</key>
                </exclude>
            </filter>
            <locales>
                <locale name="de"></locale>
                <locale name="en"></locale>
            </locales>
        </set>

    </translations>

</phpunuhi>

=== boxblinkracer/phpunuhi/tests/playground/php/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../xsd/phpunuhi.xsd"
>

    <translations>

        <set name="php">
            <format>
                <php sort="true"/>
            </format>
            <locales>
                <locale name="de">./de.php</locale>
                <locale name="en">./en.php</locale>
                <locale name="fr">./fr.php</locale>
            </locales>
        </set>

    </translations>

</phpunuhi>

=== boxblinkracer/phpunuhi/tests/playground/json/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../xsd/phpunuhi.xsd"
>

    <translations>

        <set name="json">
            <format>
                <json indent="2" sort="true"/>
            </format>
            <styles>
                <style>kebab</style>
            </styles>
            <locales>
                <locale name="de">./de.json</locale>
                <locale name="nl">./nl.json</locale>
            </locales>

        </set>

    </translations>

</phpunuhi>

=== boxblinkracer/phpunuhi/tests/playground/yaml/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../xsd/phpunuhi.xsd"
>

    <translations>

        <set name="yaml">
            <format>
                <yaml sort="true"/>
            </format>
            <locales>
                <locale name="de">./de.yaml</locale>
                <locale name="en">./en.yaml</locale>
                <locale name="fr">./fr.yaml</locale>
            </locales>
        </set>

    </translations>


    <coverage>
        <locale name="de">20</locale>
    </coverage>

</phpunuhi>

=== boxblinkracer/phpunuhi/tests/playground/ini/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../xsd/phpunuhi.xsd"
>

    <translations>

        <set name="ini">
            <format>
                <ini sort="true"/>
            </format>
            <styles>
                <style>camel</style>
            </styles>
            <locales>
                <locale name="de">./de.ini</locale>
                <locale name="en">./en.ini</locale>
                <locale name="fr">./fr.ini</locale>
            </locales>
        </set>

        <set name="ini_sections">
            <format>
                <ini sort="true"/>
            </format>
            <locales>
                <locale name="de" iniSection="de">./ini_sections.ini</locale>
                <locale name="en" iniSection="en">./ini_sections.ini</locale>
            </locales>
        </set>

    </translations>

</phpunuhi>
